@Postech.Hackathon.Agenda.Api_HostAddress = http://localhost:5054
@jwt = seu_token_jwt_aqui

GET {{Postech.Hackathon.Agenda.Api_HostAddress}}/weatherforecast/
Accept: application/json

### Agendamento - Obter por ID
GET {{Postech.Hackathon.Agenda.Api_HostAddress}}/api/agendamento/{{agendamentoId}}
Accept: application/json
Authorization: Bearer {{jwt}}

### Agendamento - Criar
POST {{Postech.Hackathon.Agenda.Api_HostAddress}}/api/agendamento
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "dataHora": "2024-04-06T10:00:00",
    "medicoId": "00000000-0000-0000-0000-000000000000",
    "pacienteId": "00000000-0000-0000-0000-000000000000"
}

### Agendamento - Obter por Médico
POST {{Postech.Hackathon.Agenda.Api_HostAddress}}/api/agendamento/oberpormedico
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "medicoId": "00000000-0000-0000-0000-000000000000",
    "dataInicio": "2024-04-01",
    "dataFim": "2024-04-30"
}

### Agendamento - Obter por Paciente
POST {{Postech.Hackathon.Agenda.Api_HostAddress}}/api/agendamento/obterporpaciente
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "pacienteId": "00000000-0000-0000-0000-000000000000",
    "dataInicio": "2024-04-01",
    "dataFim": "2024-04-30"
}

### Agendamento - Recusar
POST {{Postech.Hackathon.Agenda.Api_HostAddress}}/api/agendamento/recusar
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "agendamentoId": "00000000-0000-0000-0000-000000000000",
    "motivo": "Motivo da recusa"
}

### Agendamento - Aprovar
POST {{Postech.Hackathon.Agenda.Api_HostAddress}}/api/agendamento/aprovar
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "agendamentoId": "00000000-0000-0000-0000-000000000000"
}

### Horário Disponível - Criar
POST {{Postech.Hackathon.Agenda.Api_HostAddress}}/api/horariodisponivel
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "medicoId": "00000000-0000-0000-0000-000000000000",
    "dataHora": "2024-04-06T10:00:00",
    "duracao": 30
}

### Horário Disponível - Alterar
PUT {{Postech.Hackathon.Agenda.Api_HostAddress}}/api/horariodisponivel
Content-Type: application/json
Authorization: Bearer {{jwt}}

{
    "id": "00000000-0000-0000-0000-000000000000",
    "medicoId": "00000000-0000-0000-0000-000000000000",
    "dataHora": "2024-04-06T10:00:00",
    "duracao": 45
}

### Horário Disponível - Obter por Médico
GET {{Postech.Hackathon.Agenda.Api_HostAddress}}/api/horariodisponivel/obterhorariospormedico/{{medicoId}}
Accept: application/json
Authorization: Bearer {{jwt}}

###
